# Generated by Django 3.2 on 2021-07-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usersbase_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersbase',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
