# Generated by Django 3.2 on 2021-07-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210726_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statut',
            options={'verbose_name_plural': 'Statuts'},
        ),
    ]
