# Generated by Django 3.2 on 2021-07-28 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_statut_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbase',
            name='statut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statut', to='users.statut'),
        ),
    ]
