# Generated by Django 3.2 on 2021-08-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20210811_1235'),
        ('users', '0007_alter_usersbase_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersbase',
            name='team',
            field=models.ManyToManyField(to='team.Team'),
        ),
    ]
