# Generated by Django 3.2 on 2021-08-11 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20210811_1235'),
        ('users', '0008_usersbase_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersbase',
            name='team',
        ),
        migrations.AddField(
            model_name='usersbase',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='team.team'),
        ),
    ]
