# Generated by Django 3.2 on 2021-08-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Final_D',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Start_D',
            field=models.DateField(null=True),
        ),
    ]
