# Generated by Django 3.2 on 2021-08-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet', '0003_task_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
