# Generated by Django 3.2 on 2021-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet', '0004_projet_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='Final_D',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='Start_D',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default='0', max_length=100),
        ),
    ]
