# Generated by Django 3.2 on 2021-08-16 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projet', '0005_auto_20210809_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.PositiveSmallIntegerField(default='0', max_length=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
