# Generated by Django 3.2 on 2021-07-28 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('chef_Projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CP', to=settings.AUTH_USER_MODEL)),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M1', to=settings.AUTH_USER_MODEL)),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M2', to=settings.AUTH_USER_MODEL)),
                ('member3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M3', to=settings.AUTH_USER_MODEL)),
                ('member4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M4', to=settings.AUTH_USER_MODEL)),
                ('member5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M5', to=settings.AUTH_USER_MODEL)),
                ('member6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M6', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
