# Generated by Django 3.2 on 2021-07-28 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='chef_Projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CP', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M1', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M2', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M3', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M4', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='M5', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
