# Generated by Django 3.2 on 2021-07-28 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_auto_20210728_1257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterField(
            model_name='team',
            name='chef_Projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CP', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M1', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M2', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M3', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M4', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='M5', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('chef_Projet', 'member1', 'member2', 'member3', 'member4', 'member5', 'member6')},
        ),
    ]
