# Generated by Django 3.2 on 2021-07-28 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0004_auto_20210728_1313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='team',
            index_together={('chef_Projet', 'member1', 'member2', 'member3', 'member4', 'member5', 'member6')},
        ),
    ]
