# Generated by Django 3.2 on 2021-08-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20210728_1323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='team',
            name='chef_Projet',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member5',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member6',
        ),
    ]
